AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Local DynamoDB tables for HydroSatKevin development

Resources:
  # DynamoDB Tables for Local Development
  LocalFeedbackTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: hydrosatkevin-local-feedback
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: idempotencyKey
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: IdempotencyIndex
          KeySchema:
            - AttributeName: idempotencyKey
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  LocalStatisticsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: hydrosatkevin-local-statistics
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

Outputs:
  LocalFeedbackTableName:
    Description: DynamoDB table name for local feedback
    Value: !Ref LocalFeedbackTable
    Export:
      Name: hydrosatkevin-local-feedback-table

  LocalStatisticsTableName:
    Description: DynamoDB table name for local statistics
    Value: !Ref LocalStatisticsTable
    Export:
      Name: hydrosatkevin-local-statistics-table